[pytest]
addopts = -v -s
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
markers =
    users: Маркировка тестов связанных с работой над пользователями.
    files: Маркировка тестов связанных с работой над файлами.
    authentication: Маркировка тестов связанных с аутентификацией пользователей.
    regression: Маркировка для регрессионных тестов.